version: '3.8'

services:
  postgres:
    image: postgres:latest
    container_name: curso_sql_db
    environment:
      POSTGRES_USER: curso_user
      POSTGRES_PASSWORD: curso_password
      POSTGRES_DB: curso_sql
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
    networks:
      - curso_sql_network

  pgadmin:
    image: dpage/pgadmin4:latest
    container_name: curso_sql_pgadmin
    environment:
      PGADMIN_DEFAULT_EMAIL: admin@admin.com
      PGADMIN_DEFAULT_PASSWORD: admin
    ports:
      - "5050:80"
    depends_on:
      - postgres
    networks:
      - curso_sql_network

volumes:
  postgres_data:

networks:
  curso_sql_network:
    driver: bridge 